### ISSUE TITLE
Unexpected EOF error while setting load_balancer to create JCS instance

### ISSUE THREAD

**Issue by atjapan2015** [terraform-providers/terraform-provider-oraclepaas#66]
Hi,

While creating JCS with OCI-Managed Load Balancer, I set below contents in tf file.
`
  load_balancer {
    subnets =[
      "${oci_core_subnet.subnet1.id}",
      "${oci_core_subnet.subnet2.id}"
    ]

    load_balancing_policy = "ROUND_ROBIN"
  }
`

but got error below,
---
error(s) occurred:
*   oraclepaas_java_service_instance.jcs: 1 error(s) occurred:
*   oraclepaas_java_service_instance.jcs: unexpected EOF
---

After investigating resource_java_service_instance.go file,
around line 686 ~ 693, maybe the Type of subnets should be "schema.TypeList",
not "schema.TypeSet".

What's more, because oracle has launched single AD region toronto,
the value of "MinItems" should be 1, not 2 anymore.

Could anyone check above problem?

Thanks!

**Comment by mbfrahry** [comment]
Hey @atjapan2015, thanks for submitting this issue. Do you happen to have the full stack trace for the error?

**Comment by atjapan2015** [comment]
Hey @mbfrahry 
Yes. Below are stack trace for your reference.
`
Error: Error applying plan:

1 error(s) occurred:

* oraclepaas_java_service_instance.jcs: 1 error(s) occurred:

* oraclepaas_java_service_instance.jcs: unexpected EOF

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.


panic: interface conversion: interface {} is *schema.Set, not []interface {}
2019-04-03T15:33:04.321+0800 [DEBUG] plugin.terraform-provider-oraclepaas_v1.4.3_x4: 
2019-04-03T15:33:04.321+0800 [DEBUG] plugin.terraform-provider-oraclepaas_v1.4.3_x4: goroutine 139 [running]:
2019-04-03T15:33:04.321+0800 [DEBUG] plugin.terraform-provider-oraclepaas_v1.4.3_x4: github.com/terraform-providers/terraform-provider-oraclepaas/oraclepaas.getStringList(0xc00027c4d0, 0xe5b029, 0x17, 0x7, 0xc00064d978, 0xc000622000)
2019-04-03T15:33:04.321+0800 [DEBUG] plugin.terraform-provider-oraclepaas_v1.4.3_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oraclepaas/oraclepaas/helpers.go:39 +0x1f2
2019-04-03T15:33:04.321+0800 [DEBUG] plugin.terraform-provider-oraclepaas_v1.4.3_x4: github.com/terraform-providers/terraform-provider-oraclepaas/oraclepaas.expandLoadBalancer(0xc00027c4d0, 0xc000659850)
2019-04-03T15:33:04.321+0800 [DEBUG] plugin.terraform-provider-oraclepaas_v1.4.3_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oraclepaas/oraclepaas/resource_java_service_instance.go:952 +0x1b2
2019-04-03T15:33:04.321+0800 [DEBUG] plugin.terraform-provider-oraclepaas_v1.4.3_x4: github.com/terraform-providers/terraform-provider-oraclepaas/oraclepaas.resourceOraclePAASJavaServiceInstanceCreate(0xc00027c4d0, 0xca7f80, 0xc00051b280, 0xc00027c4d0, 0x0)
2019-04-03T15:33:04.321+0800 [DEBUG] plugin.terraform-provider-oraclepaas_v1.4.3_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oraclepaas/oraclepaas/resource_java_service_instance.go:786 +0x9fa
2019-04-03T15:33:04.321+0800 [DEBUG] plugin.terraform-provider-oraclepaas_v1.4.3_x4: github.com/terraform-providers/terraform-provider-oraclepaas/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc00019bf80, 0xc000271130, 0xc000434c60, 0xca7f80, 0xc00051b280, 0x40b801, 0xc0000b9b80, 0x4c0f4c)
2019-04-03T15:33:04.321+0800 [DEBUG] plugin.terraform-provider-oraclepaas_v1.4.3_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oraclepaas/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:225 +0x351
2019-04-03T15:33:04.321+0800 [DEBUG] plugin.terraform-provider-oraclepaas_v1.4.3_x4: github.com/terraform-providers/terraform-provider-oraclepaas/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc0001350a0, 0xc0002710e0, 0xc000271130, 0xc000434c60, 0xc000030a80, 0x1000, 0x7fe93622e6c0)
2019-04-03T15:33:04.321+0800 [DEBUG] plugin.terraform-provider-oraclepaas_v1.4.3_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oraclepaas/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:283 +0x9c
2019-04-03T15:33:04.321+0800 [DEBUG] plugin.terraform-provider-oraclepaas_v1.4.3_x4: github.com/terraform-providers/terraform-provider-oraclepaas/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc0004357c0, 0xc000434c00, 0xc00043ccc0, 0x0, 0x0)
2019-04-03T15:33:04.321+0800 [DEBUG] plugin.terraform-provider-oraclepaas_v1.4.3_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oraclepaas/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:527 +0x57
2019-04-03T15:33:04.321+0800 [DEBUG] plugin.terraform-provider-oraclepaas_v1.4.3_x4: reflect.Value.call(0xc0000796e0, 0xc00000cb00, 0x13, 0xe493f0, 0x4, 0xc0000b9f18, 0x3, 0x3, 0xc0000c1c00, 0x0, ...)
2019-04-03T15:33:04.321+0800 [DEBUG] plugin.terraform-provider-oraclepaas_v1.4.3_x4: 	/opt/goenv/versions/1.11.4/src/reflect/value.go:447 +0x454
2019-04-03T15:33:04.321+0800 [DEBUG] plugin.terraform-provider-oraclepaas_v1.4.3_x4: reflect.Value.Call(0xc0000796e0, 0xc00000cb00, 0x13, 0xc0002f0718, 0x3, 0x3, 0x5d64ab, 0xc0002f0728, 0x429832)
2019-04-03T15:33:04.321+0800 [DEBUG] plugin.terraform-provider-oraclepaas_v1.4.3_x4: 	/opt/goenv/versions/1.11.4/src/reflect/value.go:308 +0xa4
2019-04-03T15:33:04.321+0800 [DEBUG] plugin.terraform-provider-oraclepaas_v1.4.3_x4: net/rpc.(*service).call(0xc000619f40, 0xc0000a7ae0, 0xc000433950, 0xc000433970, 0xc00012f180, 0xc000435860, 0xcaed40, 0xc000434c00, 0x16, 0xcaed80, ...)
2019-04-03T15:33:04.321+0800 [DEBUG] plugin.terraform-provider-oraclepaas_v1.4.3_x4: 	/opt/goenv/versions/1.11.4/src/net/rpc/server.go:384 +0x14e
2019-04-03T15:33:04.321+0800 [DEBUG] plugin.terraform-provider-oraclepaas_v1.4.3_x4: created by net/rpc.(*Server).ServeCodec
2019-04-03T15:33:04.321+0800 [DEBUG] plugin.terraform-provider-oraclepaas_v1.4.3_x4: 	/opt/goenv/versions/1.11.4/src/net/rpc/server.go:481 +0x47e
2019/04/03 15:33:04 [TRACE] root: eval: *terraform.EvalWriteState
2019/04/03 15:33:04 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2019/04/03 15:33:04 [TRACE] root: eval: *terraform.EvalIf
2019/04/03 15:33:04 [TRACE] root: eval: *terraform.EvalWriteState
2019/04/03 15:33:04 [TRACE] root: eval: *terraform.EvalWriteDiff
2019/04/03 15:33:04 [TRACE] root: eval: *terraform.EvalApplyPost
2019-04-03T15:33:04.322+0800 [DEBUG] plugin: plugin process exited: path=/u01/workspace/iac-recipes/jcs-atp/jcs-db-terraform-provisioner_toronto/.terraform/plugins/linux_amd64/terraform-provider-oraclepaas_v1.4.3_x4
2019/04/03 15:33:04 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* oraclepaas_java_service_instance.jcs: unexpected EOF
2019/04/03 15:33:04 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* oraclepaas_java_service_instance.jcs: unexpected EOF
2019/04/03 15:33:04 [TRACE] [walkApply] Exiting eval tree: oraclepaas_java_service_instance.jcs
2019/04/03 15:33:04 [TRACE] dag/walk: upstream errored, not walking "provider.oraclepaas (close)"
2019/04/03 15:33:04 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2019/04/03 15:33:04 [TRACE] dag/walk: upstream errored, not walking "root"
2019/04/03 15:33:04 [TRACE] Preserving existing state lineage "68bca9fc-4ae8-ace9-12b3-20659d661234"
2019/04/03 15:33:04 [TRACE] Preserving existing state lineage "68bca9fc-4ae8-ace9-12b3-20659d661234"
2019/04/03 15:33:04 [TRACE] Preserving existing state lineage "68bca9fc-4ae8-ace9-12b3-20659d661234"
2019/04/03 15:33:04 [DEBUG] plugin: waiting for all plugin processes to complete...
2019-04-03T15:33:04.356+0800 [WARN ] plugin: error closing client during Kill: err="connection is shut down"
2019-04-03T15:33:04.357+0800 [DEBUG] plugin.terraform-provider-oci_v3.17.0_x4: 2019/04/03 15:33:04 [ERR] plugin: plugin server: accept unix /tmp/plugin440708825: use of closed network connection
2019-04-03T15:33:04.360+0800 [DEBUG] plugin: plugin process exited: path=/u01/workspace/iac-recipes/jcs-atp/jcs-db-terraform-provisioner_toronto/.terraform/plugins/linux_amd64/terraform-provider-oci_v3.17.0_x4



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

`

**Comment by mbfrahry** [comment]
That's just what I needed. Thanks @atjapan2015. I have a fix submitted here #67 that should address this.

**Comment by mbfrahry** [comment]
This has been released in 1.5.1 of the provider. Thank you for opening this issue @atjapan2015
